name: capc_multiservicio
description: Aplicación de escritorio local de ventas e inventario para CAPC MULTISERVICIO.
publish_to: none
version: 0.3.0+6

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite_common_ffi: ^2.4.3
  sqlite3: ^3.0.0
  path_provider: ^2.1.5
  path: ^1.9.1
  uuid: ^4.5.1
  cryptography: ^2.9.0
  intl: any
  pdf: ^3.11.3
  printing: ^5.15.1
  file_selector: ^1.0.3
  excel_community: ^2.4.0
  archive: ^4.3.0
  xml: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  file_selector_platform_interface: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/LICENSE.txt
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
